version: "3.8"
services:
  backend:
    image: node:16-bullseye
    container_name: "backend"
    ports:
      - 3001:3001
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/app
    command: ["yarn", "--cwd", "/app", "start:dev"]
    networks:
      - "kanji-cluster"
  server:
    depends_on:
      - frontend
      - backend
    image: nginx
    volumes:
      - ./backend.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8081:80
    networks:
      - "kanji-cluster"
networks:
  kanji-cluster:
    driver: bridge
